name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Print source directory to check Cargo.toml
      run: cd /home/runner/work/worm/worm/worm
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

